/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By
 * starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 *
 * Answer: 4613732
 */

pub fn run() -> u32 {
    let mut fib: [u32; 2] = [1, 1];
    let mut sum: u32 = 0;

    while fib[1] < 4_000_000 {
        if fib[1] % 2 == 0 {
            sum += fib[1];
        }

        fib[1] += fib[0];
        fib[0] = fib[1] - fib[0];
    }

    return sum;
}